urls:
  driverLocations:
    path: "/drivers/:id/locations"
    method: "PATCH"
    nsq:
      nsqLookupdAddress: "nsqlookupd:4161"
      nsqdAddress: "nsqd:4150"
      topic: "locations"
      maxInFlight: 25
      channel: "store_location"
      handlerConcurrency: 4
  zombieDriver:
    path: "/drivers/:id"
    method: "GET"
    http:
      host: "zombie_driver"
servers:
  internal:
    address: "zombie_driver"
    port: "8082"
  external:
    address: ""
    port: "8081"