version: '3'

services:
  driver_location:
    image: farzadras/driver_location
    ports:
      - "8083:8083"
    depends_on:
      - nsqlookupd
      - redis

  gateway:
    image: farzadras/gateway
    ports:
      - "8081:8081"
    depends_on:
      - nsqlookupd

  zombie_driver:
    image: farzadras/zombie_driver
    ports:
      - "8082:8082"

