version: '3'

services:
  configserver:
    image: farzadras/configserver
    ports:
      - "8888:8888"
    depends_on:
      - rabbitmq
    restart: always

  nsqd:
    image: nsqio/nsq:v0.3.8
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    ports:
      - "4171:4171"
    depends_on:
      - nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0-rc2
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0-rc2
    command: logstash -f /config-dir/logstash.conf
    links:
      - elasticsearch:elasticsearch
    ports:
      - 9500:9500/udp
    depends_on:
      - elasticsearch
    volumes:
      - "../../../elk:/config-dir"

volumes:
  elk:
