version: '3'

services:
  rabbitmq:
    image: farzadras/rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"

  nsqlookupd:
    image: nsqio/nsq:v0.3.8
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-rc2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  alpine:
    image: alpine
    command: ping java.com
    logging:
      driver: gelf
      options:
        gelf-address: udp://logstash:9500
    links:
      - logstash:logstash
    
