version: '3'

services:
  driver_location:
    image: farzadras/driver_location
    ports:
      - "8083:8083"
    depends_on:
      - nsqlookupd
      - redis
    logging:
      driver: gelf
      options:
        gelf-address: "logstash:9500"
        gelf-compression-type: "none"

  gateway:
    image: farzadras/gateway
    ports:
      - "8081:8081"
    depends_on:
      - nsqlookupd
    logging:
      driver: gelf
      options:
        gelf-address: "logstash:9500"
        gelf-compression-type: "none"

  zombie_driver:
    image: farzadras/zombie_driver
    ports:
      - "8082:8082"
    logging:
      driver: gelf
      options:
        gelf-address: "logstash:9500"
        gelf-compression-type: "none"

