version: '3'

services:
  nsqd:
    image: nsqio/nsq:v0.3.8
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=nsqd
    depends_on:
      - nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    ports:
      - "4171:4171"
    depends_on:
      - nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

  driver_location:
    image: farzadras/driver_location
    ports:
      - "8083:8083"
    depends_on:
      - nsqlookupd
      - redis

