version: '3'

services:
  configserver:
    image: farzadras/configserver
    ports:
      - "8888:8888"
    links:
      - rabbitmq:rabbitmq
    restart: always

  rabbitmq:
    image: farzadras/rabbitmq
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"

  redis:
    image: redis:5.0.3-alpine
    ports:
      - "6379:6379"

  nsqlookupd:
    image: nsqio/nsq:v0.3.8
    command: /nsqlookupd
    ports:
      - "4160:4160"
      - "4161:4161"

  nsqd:
    image: nsqio/nsq:v0.3.8
    command: /nsqd --lookupd-tcp-address=nsqlookupd:4160 --broadcast-address=127.0.0.1
    links:
      - nsqlookupd:nsqlookupd
    ports:
      - "4150:4150"
      - "4151:4151"

  nsqadmin:
    image: nsqio/nsq:v0.3.8
    ports:
      - "4171:4171"
    links:
      - nsqlookupd:nsqlookupd
    command: /nsqadmin --lookupd-http-address=nsqlookupd:4161

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.0.0-rc2
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

  kibana:
    image: docker.elastic.co/kibana/kibana:7.0.0-rc2
    links:
      - elasticsearch:elasticsearch
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
    restart: always

  logstash:
    image: docker.elastic.co/logstash/logstash:7.0.0-rc2
    command: logstash -f /config-dir/logstash.conf
    links:
      - elasticsearch:elasticsearch
    ports:
      - 9500:9500
    depends_on:
      - elasticsearch
    volumes:
      - "../../../elk:/config-dir"

  driver_location:
    image: farzadras/driver_location
    ports:
      - "8083:8083"
    depends_on:
      - nsqlookupd
      - redis
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:9500
        gelf-compression-type: "none"
    links:
      - logstash:logstash
    depends_on:
      - logstash

  gateway:
    image: farzadras/gateway
    ports:
      - "8081:8081"
    depends_on:
      - nsqlookupd
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:9500
        gelf-compression-type: "none"
    links:
      - logstash:logstash
    depends_on:
      - logstash

  zombie_driver:
    image: farzadras/zombie_driver
    ports:
      - "8082:8082"
    logging:
      driver: gelf
      options:
        gelf-address: udp://localhost:9500
        gelf-compression-type: "none"
    links:
      - logstash:logstash
    depends_on:
      - logstash

volumes:
  elk:
