FROM golang:alpine as builder
ARG moduleName
RUN mkdir -p /go/src/github.com/farzadrastegar/simple-cab/${moduleName}
RUN mkdir -p /go/src/github.com/farzadrastegar/simple-cab/vendor
ENV GOPATH /go
ADD ${moduleName}/ /go/src/github.com/farzadrastegar/simple-cab/${moduleName}/
ADD vendor/ /go/src/github.com/farzadrastegar/simple-cab/vendor/

WORKDIR /go/src/github.com/farzadrastegar/simple-cab/${moduleName}/cmd
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -ldflags '-extldflags "-static"' -o main .
FROM scratch
ARG moduleName
COPY --from=builder /go/src/github.com/farzadrastegar/simple-cab/${moduleName}/cmd/main /app/cmd/
COPY --from=builder /go/src/github.com/farzadrastegar/simple-cab/${moduleName}/config.yaml /app/
WORKDIR /app/cmd
ENTRYPOINT ["./main", "-configServerUrl", "http://configserver:8888", "-profile", "dev", "-configBranch", "master"]
