urls:
  zombieStatus:
    method: "GET"
    path: "/drivers/:id"
    definition:
      distance: 500.0 #meters
      duration: 5.0 #minutes
servers:
  zombie_driver:
    address: "localhost"
    port: "8082"
  driver_location:
    address: "localhost"
    port: "8083"