urls:
  zombieStatus:
    method: "GET"
    path: "/drivers/:id"
    definition:
      distance: 2000.0 #meters
      duration: 0.3334 #minutes
servers:
  zombie_driver:
    address: ""
    port: "8082"
  driver_location:
    address: ""
    port: "8083"