urls:
  driverLocations:
    method: "GET"
    path: "/drivers/:id/locations"
    nsq:
      nsqLookupdAddress: ":4161"
      nsqdAddress: ":4150"
      topic: "locations"
      maxInFlight: 25
      channel: "store_location"
      handlerConcurrency: 4
server:
  address: ""
  port: "8083"
database:
  address: ""
  port: "6379"
  passwrod: ""
  db: 0